### ISSUE TITLE
cnpm 也需要

### ISSUE THREAD

**Issue by xiaohuoni** [ycjcl868/tnpm-sync#1]
我现在是这样搞的
```
const syncRes = execa.sync('cnpm', ['sync', name]);
```

**Comment by ycjcl868** [comment]
tnpm-sync --command="cnpm sync" .

这直接用啊

**Comment by xiaohuoni** [comment]
我瞎了（捂脸）
![image](https://user-images.githubusercontent.com/11746742/79308616-7f0b7500-7f2b-11ea-8ed3-5c2e56271620.png)
